### PR TITLE
Update to v7.1.1

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Please do not merge this until #15 has been merged.

**Comment by ocefpaf** [comment]
Sorry, ended up merging #17 b/c you fixed the URL in #15. But let's get this one in too b/c it adds you as a maintainer.

**Comment by xylar** [comment]
I was added already in #15 but I'm pretty sure merging this PR does no harm.

**Comment by xylar** [comment]
And thanks!

**Pull request merged**
